import uuid
import datetime
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ProposalStatus(str, Enum):
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    IMPLEMENTED = "implemented"

class StrategyProposal(BaseModel):
    """
    Generated by the Learning Engine when it detects an optimization opportunity.
    Must be human-approved before modifying the Business Brain.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tenant_id: str
    title: str
    description: str
    
    # Explainability Data
    evidence: List[str] = Field(default_factory=list) # e.g. ["Call drop off at pricing increased 15%"]
    proposed_changes: Dict[str, Any] = Field(default_factory=dict) # Diff of BusinessBrain modifications
    
    status: ProposalStatus = ProposalStatus.PENDING_REVIEW
    created_at: str = Field(default_factory=lambda: datetime.datetime.utcnow().isoformat())

class ForecastMetrics(BaseModel):
    total_prospects: int = 0
    meetings_booked: int = 0
    pipeline_value: float = 0.0

class RevenueForecast(BaseModel):
    """
    Hybrid Forecasting Model (Deterministic + Statistical + AI Narrative).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tenant_id: str
    
    # Deterministic Data
    deterministic: ForecastMetrics = Field(default_factory=ForecastMetrics)
    
    # Predictive Data (Machine Learning models)
    statistical_variance_low: float = 0.0
    statistical_variance_high: float = 0.0
    
    # Explainability Narrative
    ai_narrative: str
    
    generated_at: str = Field(default_factory=lambda: datetime.datetime.utcnow().isoformat())
