from typing import Any, Dict, Optional
from fastapi import Request, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

class ProblemDetails(BaseModel):
    """
    RFC 7807 compliant problem details model for HTTP error responses.
    """
    type: str = Field(..., description="A URI reference that identifies the problem type.")
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(..., description="The HTTP status code generated by the origin server.")
    detail: str = Field(..., description="A human-readable explanation specific to this occurrence.")
    instance: Optional[str] = Field(None, description="A URI reference that identifies the specific occurrence.")
    invalid_params: Optional[list] = Field(None, description="For validation errors, the list of invalid fields and details.")

class SecurityException(HTTPException):
    """
    Base security exception.
    """
    def __init__(
        self, 
        status_code: int, 
        detail: str, 
        title: str = "Security Error",
        error_type: str = "about:blank",
        invalid_params: Optional[list] = None
    ):
        super().__init__(status_code=status_code, detail=detail)
        self.title = title
        self.error_type = error_type
        self.invalid_params = invalid_params

class AuthenticationException(SecurityException):
    """
    Raised when authentication credentials are missing, invalid, or expired.
    """
    def __init__(self, detail: str, error_type: str = "https://visoora.com/errors/unauthenticated"):
        super().__init__(
            status_code=401,
            detail=detail,
            title="Authentication Failed",
            error_type=error_type
        )

class AuthorizationException(SecurityException):
    """
    Raised when authenticated user lacks the required RBAC role permissions.
    """
    def __init__(self, detail: str, error_type: str = "https://visoora.com/errors/forbidden"):
        super().__init__(
            status_code=403,
            detail=detail,
            title="Forbidden Access",
            error_type=error_type
        )

class RateLimitExceededException(SecurityException):
    """
    Raised when the tenant-based sliding window rate limits are breached.
    """
    def __init__(self, detail: str, error_type: str = "https://visoora.com/errors/rate-limit-exceeded"):
        super().__init__(
            status_code=429,
            detail=detail,
            title="Rate Limit Exceeded",
            error_type=error_type
        )

async def rfc7807_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """
    Translates HTTPExceptions, SecurityExceptions, and other unhandled exceptions 
    into standard RFC 7807 Problem Details JSON format.
    """
    status_code = 500
    title = "Internal Server Error"
    detail = "An unexpected error occurred. Please contact system support."
    error_type = "about:blank"
    invalid_params = None
    
    correlation_id = getattr(request.state, "correlation_id", "unknown")
    
    if isinstance(exc, SecurityException):
        status_code = exc.status_code
        title = exc.title
        detail = exc.detail
        error_type = exc.error_type
        invalid_params = exc.invalid_params
    elif isinstance(exc, HTTPException):
        status_code = exc.status_code
        detail = str(exc.detail)
        if status_code == 401:
            title = "Unauthorized"
            error_type = "https://visoora.com/errors/unauthenticated"
        elif status_code == 403:
            title = "Forbidden"
            error_type = "https://visoora.com/errors/forbidden"
        elif status_code == 404:
            title = "Resource Not Found"
            error_type = "https://visoora.com/errors/not-found"
        else:
            title = "HTTP Error"
    else:
        # Fallback log of unexpected failures (hiding actual stack trace from response)
        # Detailed traceback will be printed in server logs via structlog
        detail = f"System error reference: {correlation_id}"

    # Build ProblemDetails payload
    payload = ProblemDetails(
        type=error_type,
        title=title,
        status=status_code,
        detail=detail,
        instance=request.url.path,
        invalid_params=invalid_params
    )
    
    headers = {"Content-Type": "application/problem+json"}
    if status_code == 401:
        headers["WWW-Authenticate"] = 'Bearer error="invalid_token"'

    return JSONResponse(
        status_code=status_code,
        content=payload.model_dump(exclude_none=True),
        headers=headers
    )
