import datetime
from typing import Dict, List, Any, Optional
from uuid import UUID
from enum import Enum
from pydantic import BaseModel, Field, field_validator, ConfigDict


# ====================================================
# ENUMS
# ====================================================
class ActivityTypeEnum(str, Enum):
    CALL = "call"
    EMAIL = "email"
    SMS = "sms"
    NOTE = "note"
    TASK = "task"


class SentimentEnum(str, Enum):
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"
    UNKNOWN = "unknown"


# ====================================================
# CONTACT MODELS
# ====================================================
class ContactBase(BaseModel):
    phone_e164: str = Field(
        ...,
        description="E.164 formatted contact phone number, e.g. +19199999999",
        examples=["+19199999999"]
    )
    email: Optional[str] = Field(
        None,
        description="Contact email address",
        examples=["prospect@cyberdyne.com"]
    )
    full_name: str = Field(
        ...,
        description="Full legal name of the contact",
        examples=["John Doe"]
    )
    title: Optional[str] = Field(
        None,
        description="Professional title or role",
        examples=["VP of Sales"]
    )
    company_name: Optional[str] = Field(
        None,
        description="Name of the company",
        examples=["Cyberdyne Systems"]
    )
    linkedin_url: Optional[str] = Field(
        None,
        description="Public LinkedIn profile URL",
        examples=["https://linkedin.com/in/johndoe"]
    )
    lead_source: Optional[str] = Field(
        None,
        description="Source of the lead generation",
        examples=["Outbound Call"]
    )
    lead_score: int = Field(
        0,
        ge=0,
        le=100,
        description="AI calculated lead score from 0 to 100 indicating deal probability",
        examples=[75]
    )
    tags: List[str] = Field(
        default_factory=list,
        description="Dynamic string tags list to label the contact",
        examples=[["enterprise", "objection-pricing"]]
    )
    custom_fields: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value pairs of dynamic metadata or custom attributes",
        examples=[{"industry_preference": "SaaS"}]
    )

    @field_validator("phone_e164")
    @classmethod
    def validate_phone(cls, v: str) -> str:
        if not v.startswith("+") or len(v) < 8 or len(v) > 18:
            raise ValueError("Phone number must be E.164 formatted starting with '+' and between 8 and 18 chars.")
        return v

    @field_validator("email")
    @classmethod
    def validate_email(cls, v: Optional[str]) -> Optional[str]:
        if v is not None:
            if "@" not in v or "." not in v or len(v) < 5:
                raise ValueError("Invalid email format.")
        return v


class ContactCreate(ContactBase):
    tenant_id: str = Field(..., description="Unique multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator user ID or AI tag")


class ContactUpdate(BaseModel):
    phone_e164: Optional[str] = Field(None, description="E.164 phone format")
    email: Optional[str] = Field(None, description="Email address")
    full_name: Optional[str] = Field(None, description="Full name")
    title: Optional[str] = Field(None, description="Job title")
    company_name: Optional[str] = Field(None, description="Company name")
    linkedin_url: Optional[str] = Field(None, description="LinkedIn profile URL")
    lead_source: Optional[str] = Field(None, description="Source of the lead")
    lead_score: Optional[int] = Field(None, ge=0, le=100, description="Lead score from 0-100")
    tags: Optional[List[str]] = Field(None, description="Tags array")
    custom_fields: Optional[Dict[str, Any]] = Field(None, description="Custom field attributes")
    updated_at: Optional[datetime.datetime] = Field(default_factory=datetime.datetime.utcnow)


class ContactResponse(ContactBase):
    id: UUID = Field(..., description="Unique identifier generated by DB")
    tenant_id: str = Field(..., description="Unique tenant identification boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Identifier of resource creator")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# COMPANY MODELS
# ====================================================
class CompanyBase(BaseModel):
    name: str = Field(..., description="Company name", examples=["Cyberdyne Systems"])
    domain: Optional[str] = Field(None, description="Company corporate website domain", examples=["cyberdyne.com"])
    industry: Optional[str] = Field(None, description="Corporate industry sector", examples=["Technology"])
    employee_count: Optional[int] = Field(None, ge=0, description="Number of corporate employees", examples=[500])
    annual_revenue: Optional[float] = Field(None, ge=0.0, description="Estimated annual revenue in USD", examples=[12000000.0])
    country: Optional[str] = Field(None, description="Country of registration", examples=["United States"])


class CompanyCreate(CompanyBase):
    tenant_id: str = Field(..., description="Multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator user ID or AI tag")


class CompanyResponse(CompanyBase):
    id: UUID = Field(..., description="Unique identifier generated by DB")
    tenant_id: str = Field(..., description="Tenant id boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Creator identity")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# PIPELINE STAGE MODELS
# ====================================================
class PipelineStageBase(BaseModel):
    name: str = Field(..., description="Name of the pipeline sales stage", examples=["Demo Booked"])
    position: int = Field(..., ge=1, description="Sort order position for pipeline display", examples=[3])
    probability_pct: int = Field(..., ge=0, le=100, description="Probability percentage of closing the deal", examples=[50])
    is_terminal: bool = Field(False, description="Indicates if stage is a terminal won/lost stage")


class PipelineStageCreate(PipelineStageBase):
    tenant_id: str = Field(..., description="Multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator user ID or AI tag")


class PipelineStageResponse(PipelineStageBase):
    id: UUID = Field(..., description="Unique stage identifier")
    tenant_id: str = Field(..., description="Tenant id boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Creator identifier")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# DEAL MODELS
# ====================================================
class DealBase(BaseModel):
    contact_id: Optional[UUID] = Field(None, description="Associated Contact ID")
    company_id: Optional[UUID] = Field(None, description="Associated Company ID")
    stage_id: UUID = Field(..., description="Associated Pipeline Stage ID")
    title: str = Field(..., description="Deal name or title", examples=["Cyberdyne Systems - 500 Agent Expansion"])
    value_usd: float = Field(0.0, ge=0.0, description="Valuation in USD", examples=[25000.0])
    currency: str = Field("USD", description="Currency standard code", examples=["USD"])
    close_date: Optional[datetime.datetime] = Field(None, description="Estimated target closing date")
    owner_id: Optional[str] = Field(None, description="Owner user ID")
    notes: Optional[str] = Field(None, description="Internal deal annotation files")
    ai_next_action: Optional[str] = Field(None, description="AI suggested next steps/action item summary", examples=["Follow up via SMS next Monday."])
    ai_sentiment: SentimentEnum = Field(SentimentEnum.UNKNOWN, description="AI detected conversation sentiment")


class DealCreate(DealBase):
    tenant_id: str = Field(..., description="Multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator identity")


class DealUpdate(BaseModel):
    contact_id: Optional[UUID] = None
    company_id: Optional[UUID] = None
    stage_id: Optional[UUID] = None
    title: Optional[str] = None
    value_usd: Optional[float] = None
    currency: Optional[str] = None
    close_date: Optional[datetime.datetime] = None
    owner_id: Optional[str] = None
    notes: Optional[str] = None
    ai_next_action: Optional[str] = None
    ai_sentiment: Optional[SentimentEnum] = None
    updated_at: Optional[datetime.datetime] = Field(default_factory=datetime.datetime.utcnow)


class DealResponse(DealBase):
    id: UUID = Field(..., description="Unique deal ID")
    tenant_id: str = Field(..., description="Tenant id boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Creator user ID or AI tag")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# ACTIVITY MODELS
# ====================================================
class ActivityBase(BaseModel):
    deal_id: Optional[UUID] = Field(None, description="Associated Deal ID")
    contact_id: Optional[UUID] = Field(None, description="Associated Contact ID")
    type: ActivityTypeEnum = Field(..., description="Type of sales touchpoint activity")
    occurred_at: datetime.datetime = Field(default_factory=datetime.datetime.utcnow, description="When touchpoint occurred")
    duration_seconds: int = Field(0, ge=0, description="Touchpoint duration in seconds")
    outcome: Optional[str] = Field(None, description="Touchpoint outcome summary", examples=["demo_booked"])
    transcript_url: Optional[str] = Field(None, description="Public transcript storage URL")
    recording_url: Optional[str] = Field(None, description="Public audio recording storage URL")
    ai_summary: Optional[str] = Field(None, description="AI structured text summary notes", examples=["Prospect requested pricing models."])
    created_by_ai: bool = Field(False, description="Toggled to true if activity is compiled autonomously by AI")


class ActivityCreate(ActivityBase):
    tenant_id: str = Field(..., description="Multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator identifier")


class ActivityResponse(ActivityBase):
    id: UUID = Field(..., description="Unique activity ID")
    tenant_id: str = Field(..., description="Tenant id boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Creator identifier")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# DEAL STAGE HISTORY MODELS
# ====================================================
class DealStageHistoryBase(BaseModel):
    deal_id: UUID = Field(..., description="Associated Deal ID")
    from_stage_id: Optional[UUID] = Field(None, description="Originating Pipeline Stage ID")
    to_stage_id: UUID = Field(..., description="Target Pipeline Stage ID")
    reason: Optional[str] = Field(None, description="Operational trigger reasoning details")
    changed_by: Optional[str] = Field(None, description="Identifier of entity triggering transition")


class DealStageHistoryCreate(DealStageHistoryBase):
    tenant_id: str = Field(..., description="Multi-tenant identifier")
    created_by: Optional[str] = Field(None, description="Creator identifier")


class DealStageHistoryResponse(DealStageHistoryBase):
    id: UUID = Field(..., description="Unique history record identifier")
    tenant_id: str = Field(..., description="Tenant id boundary")
    created_at: datetime.datetime = Field(..., description="Database insertion timestamp")
    updated_at: datetime.datetime = Field(..., description="Database modification timestamp")
    created_by: Optional[str] = Field(None, description="Creator identifier")

    model_config = ConfigDict(from_attributes=True)


# ====================================================
# API SPECIALIZED AGGREGATE SCHEMAS
# ====================================================
class StageDealsAggregate(BaseModel):
    stage_id: UUID = Field(..., description="Stage identifier")
    stage_name: str = Field(..., description="Stage name")
    position: int = Field(..., description="Sort order position")
    deals_count: int = Field(..., description="Number of deals currently in this stage")
    total_value_usd: float = Field(..., description="Sum value of deals in USD")
    deals: List[DealResponse] = Field(..., description="List of deals inside this stage")
